# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_micrograd',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/my_micrograd',
                'lib_path': 'my_micrograd'},
  'syms': { 'my_micrograd.explore': { 'my_micrograd.explore.Value': ('explore.html#value', 'my_micrograd/explore.py'),
                                      'my_micrograd.explore.Value.__init__': ('explore.html#value.__init__', 'my_micrograd/explore.py'),
                                      'my_micrograd.explore.Value.__repr__': ('explore.html#value.__repr__', 'my_micrograd/explore.py')}}}
