# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/explore.ipynb.

# %% auto 0
__all__ = ['Value']

# %% ../notebooks/explore.ipynb 2
import numpy as np

# %% ../notebooks/explore.ipynb 3
class Value:
    
    def __init__(self, data: float) -> None:
        self.data = data
        
    def __repr__(self) -> str:
        return f"Value of object: {self.data}"

# %% ../notebooks/explore.ipynb 4
Value(2)
